# Generated by Selenium IDE
# import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

class Selenium_Driver():
  def __init__(self):
    self.driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

    self.vars = {}
  
  def teardown_browser(self, method):
    self.driver.quit()

  def login(self, email, password):
    print(email)
    print(password)
    self.driver.get("https://labs.openai.com/auth/login")
    self.driver.set_window_size(1504, 1667)
    self.driver.find_element(By.ID, "username").click()
    
    self.driver.find_element(By.ID, "username").send_keys(email)
    self.driver.find_element(By.ID, "username").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "password").send_keys(password)
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
  
  def download_images(self, prompt):
    self.driver.get("https://labs.openai.com/")
    self.driver.set_window_size(1504, 1667)
    self.driver.find_element(By.CSS_SELECTOR, ".text-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".text-input").send_keys(prompt)
    self.driver.find_element(By.CSS_SELECTOR, ".text-input").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > div > .task-page-generations-img-container > .task-page-quick-actions-button > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > div > .task-page-generations-img-container > .task-page-quick-actions-button > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) .task-page-quick-actions-button > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(4) .task-page-quick-actions-button > svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(5)").click()
  
